version: 2
services:
  fluid-api:
    env_file: .env.local
    build:
      context: .
      dockerfile: ./build/Containerfile
      args:
        VERSION: "v1.0.4"
    ports:
      - 8080:8080
    depend_on:
      - database

  database:
    image: docker.io/postgres:16.3-alpine3.20
    environment:
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: fluid
      POSTGRES_USER: fluid
    volumes:
      - ./var/postgresql:/var/lib/postgresql/data
    heathz: pg_isready