// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.1-0.20240604070534-2f0ff757704b DO NOT EDIT.
package server

import (
	"net/url"
	"time"

	"github.com/google/uuid"
)

// Error client error indicates some details about error
type Error struct {
	// Detail some detail about what error means
	Detail *string `json:"detail,omitempty"`

	// Instance indicate the resource on which the operation is applied
	Instance *string `json:"instance,omitempty"`

	// Title the identifiable name
	Title *string `json:"title,omitempty"`

	// Type point uri of the title error
	Type *string `json:"type,omitempty"`
}

// Link Representation of short link, and it corresponding long url that will redirected by
type Link struct {
	// CreatedAt when the link has been created by the client
	CreatedAt time.Time `json:"createdAt"`

	// ExpiredAt when the link will be expired, so unusable
	ExpiredAt time.Time `json:"expiredAt"`

	// ID idenfitier of the registered redirection link
	ID uuid.UUID `json:"id"`

	// Long target url of the redirection
	Long url.URL `json:"long"`

	// Short the short url generated by the service from when the client will be redirected
	Short url.URL `json:"short"`
}

// LinkCreation payload to create a link redirection from long one
type LinkCreation struct {
	// Long target url of the redirection
	Long string `json:"long"`
}

// Hostname defines model for Hostname.
type Hostname = string

// LinkId defines model for LinkId.
type LinkId = uuid.UUID

// Slug defines model for Slug.
type Slug = string

// ErrorBadRequestResponse client error indicates some details about error
type ErrorBadRequestResponse = Error

// ErrorConflictResponse client error indicates some details about error
type ErrorConflictResponse = Error

// ErrorForbiddenResponse client error indicates some details about error
type ErrorForbiddenResponse = Error

// ErrorInternalServerResponse client error indicates some details about error
type ErrorInternalServerResponse = Error

// ErrorNotFoundResponse client error indicates some details about error
type ErrorNotFoundResponse = Error

// ErrorUnauthorizedResponse client error indicates some details about error
type ErrorUnauthorizedResponse = Error

// LinkCreatedResponse Representation of short link, and it corresponding long url that will redirected by
type LinkCreatedResponse = Link

// LinkGetResponse Representation of short link, and it corresponding long url that will redirected by
type LinkGetResponse = Link

// LinkListResponse defines model for LinkListResponse.
type LinkListResponse = []Link

// LinkCreationRequest payload to create a link redirection from long one
type LinkCreationRequest = LinkCreation

// LinkCreateJSONRequestBody defines body for LinkCreate for application/json ContentType.
type LinkCreateJSONRequestBody = LinkCreation
