openapi: 3.1.0
info:
  title: Lilshirt
  description: This API create reduces URL and redirect flux from reduced registered URL
  version: 1.0.0

paths:
  /shortcuts:
    post:
    get:
  /shortcuts/{shortcutId}:
    get:
    delete:
  /shortcuts/{shortcutId}/stats:
    get:
  /shortcuts/{shortcutId}/stats:
    get:
  /{domain}/{slug}:
    get:

components:
  schemas:
      Shortcut: